name: exemplo

on:
  schedule:
    - cron: "0*/24 * * * "

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  hello:
    runs-on: macos-latest
    steps:
      - name: mostrar-mensagem
        run: echo "hello desenv framework II"
